---
doctrine:
    dbal:
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType

    orm:
        mappings:
            IDCIDocumentManagementBundle: { prefix: "IDCI\\Bundle\\DocumentManagementBundle\\Model" }

fos_rest:
    param_fetcher_listener: true
    routing_loader:
        default_format: json
    view:
        default_engine: twig
        force_redirects:
            html: true
        formats:
            json: true
            xml: true
            html: true
        templating_formats:
            html: false
        failed_validation: HTTP_BAD_REQUEST
    body_listener:
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml
    format_listener:
        rules:
            - { path: '/generate$', stop: true }
            - { path: '^/api/(templates|documents)', fallback_format: 'json', prefer_extension: false }
            - { path: '^/', stop: true }

knp_snappy:
    pdf:
        enabled: true
        binary: "%document_management_snappy_pdf_binary_path%"
        options:
            margin_bottom: 0
            margin_left: 0
            margin_right: 0
            margin_top: 0
