---
templates:
    resource: IDCI\Bundle\DocumentManagementBundle\Controller\Api\Rest\TemplateController
    type:     rest

documents:
    resource: IDCI\Bundle\DocumentManagementBundle\Controller\Api\Rest\DocumentController
    type:     rest

generate:
    resource: "@IDCIDocumentManagementBundle/Controller/Api/GeneratorController.php"
    type:     annotation
