parameters:
    idci_document.generator.class: IDCI\Bundle\DocumentManagementBundle\Generator\Generator

    idci_document.converter.registry.class: IDCI\Bundle\DocumentManagementBundle\Converter\ConverterRegistry
    idci_document.converter.html.class: IDCI\Bundle\DocumentManagementBundle\Converter\HtmlConverter
    idci_document.converter.pdf.class: IDCI\Bundle\DocumentManagementBundle\Converter\PdfConverter

    idci_document.model.template.class: IDCI\Bundle\DocumentManagementBundle\Model\Template

    idci_document.repository.template.class: IDCI\Bundle\DocumentManagementBundle\Repository\TemplateRepository

services:

    ## Generator
    idci_document.generator:
        class: IDCI\Bundle\DocumentManagementBundle\Generator\Generator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@idci_document.converter.registry"
            - "@twig"

    ## Registry
    idci_document.converter.registry:
        class: "%idci_document.converter.registry.class%"

    ## Converter
    idci_document.converter.html:
        class: "%idci_document.converter.html.class%"
        tags:
            - { name: idci_document.converter, alias: html }

    idci_document.converter.pdf:
        class: "%idci_document.converter.pdf.class%"
        arguments: ["@knp_snappy.pdf"]
        tags:
            - { name: idci_document.converter, alias: pdf }

    ## FormType
    IDCI\Bundle\DocumentManagementBundle\Form\ApiDocumentType:
        arguments: ['@doctrine.orm.entity_manager']
        tags: [form.type]
